# ???
server:
  port: 9001


# ????
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'


# ??Mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      # 表前缀
      table-prefix: bz_
      # 主键自增
      id-type: auto
  configuration:
    # 是否开启驼峰命名
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ??sql??


spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.41.110:3306/baizhanshopping?serverTimezone=UTC
    username: root
    password: 123456


dubbo:
  application:
    name: shopping_goods_service # 项目名称
  registry:
    address: zookeeper://192.168.41.110 # 服务ip
    port: 2181 # 服务端口
    timeout: 10000 # 超时时间,ms
  protocol:
    name: dubbo # dubbo协议
    port: -1 # 端口选择
  scan:
    base-packages: com.shopping.shopping_goods_service.service # 包扫描



